---
cns_version_file: cns-v1.34.6.txt

pod_network_cidr: 192.168.0.0/16
service_cidr: 10.96.0.0/12
kubeadm_cri_socket: unix:///run/containerd/containerd.sock

docker_repo_arch_map:
  x86_64: amd64
  amd64: amd64
  aarch64: arm64
  arm64: arm64

helm_arch_map:
  x86_64: amd64
  amd64: amd64
  aarch64: arm64
  arm64: arm64

control_plane_endpoint: ""
gpu_operator_namespace: gpu-operator
