[kube_control_plane]
cp1 ansible_host=10.176.203.145 ansible_user=nvidia ansible_ssh_pass='nvidia3D!' ansible_become_pass='nvidia3D!'

[kube_node]
# Uncomment and edit if you want worker nodes.
# worker1 ansible_host=192.0.2.11 ansible_user=ubuntu ansible_ssh_pass=change_me ansible_become_pass=change_me
# worker2 ansible_host=192.0.2.12 ansible_user=ubuntu ansible_ssh_pass=change_me ansible_become_pass=change_me
